services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: sleepuser
      POSTGRES_PASSWORD: sleeppass
      POSTGRES_DB: sleepdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://sleepuser:sleeppass@postgres/sleepdb
      - SECRET_KEY=your-secret-key
    depends_on:
      - postgres  # Start after postgres, but don't wait for health

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend  # Start after backend, but don't wait for health

volumes:
  pgdata: