version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - naplett-network

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_URL=http://backend:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - naplett-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Optional: Add if you need host access
    networks:
      - naplett-network

networks:
  naplett-network:
    driver: bridge

volumes:
  postgres_data: